# Generated by Django 4.2.16 on 2024-10-16 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(default='empty_404', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_item_code', message='Item code must be alphanumeric and can include underscores only.', regex='^[\\w]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
