# Generated by Django 4.2.16 on 2024-10-16 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_inventoryitem_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_item_code', message='Item code must be lowercase, alphanumeric, and can include underscores only.', regex='^[a-z0-9_]+$')]),
        ),
    ]
